"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-04 19:34:58.746270
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("profile", sa.String(), nullable=False),
        sa.Column("rule", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("opened_ms", sa.BigInteger(), nullable=False),
        sa.Column("closed_ms", sa.BigInteger(), nullable=True),
        sa.Column("clear_count", sa.BigInteger(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_profile_rule_status"), ["profile", "rule", "status"], unique=False)

    op.create_table(
        "blobs",
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("sha256", name=op.f("pk_blobs")),
    )
    op.create_table(
        "clusters",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("profile", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("likely_cause", sa.String(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("suggested_fix", sa.String(), nullable=True),
        sa.Column("cause_status", sa.String(), nullable=True),
        sa.Column("centroid", sa.LargeBinary(), nullable=True),
        sa.Column("radius", sa.Double(), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("named_members", sa.JSON(), nullable=False),
        sa.Column("created_ms", sa.BigInteger(), nullable=False),
        sa.Column("updated_ms", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clusters")),
    )
    op.create_table(
        "exchanges",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.Column("parent_span_id", sa.String(), nullable=True),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("upstream", sa.String(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("query", sa.String(), nullable=False),
        sa.Column("request_headers", sa.JSON(), nullable=False),
        sa.Column("request_blob", sa.String(), nullable=True),
        sa.Column("request_key", sa.String(), nullable=False),
        sa.Column("status", sa.BigInteger(), nullable=True),
        sa.Column("response_headers", sa.JSON(), nullable=False),
        sa.Column("response_blob", sa.String(), nullable=True),
        sa.Column("stream", sa.Boolean(), nullable=False),
        sa.Column("chunk_times", sa.JSON(), nullable=False),
        sa.Column("started_ms", sa.BigInteger(), nullable=False),
        sa.Column("first_byte_ms", sa.BigInteger(), nullable=True),
        sa.Column("ended_ms", sa.BigInteger(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("served_from", sa.String(), nullable=False),
        sa.Column("divergence", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchanges")),
    )
    with op.batch_alter_table("exchanges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exchanges_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_exchanges_trace_id_seq"), ["trace_id", "seq"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("lane", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempts", sa.BigInteger(), nullable=False),
        sa.Column("available_ms", sa.BigInteger(), nullable=False),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("created_ms", sa.BigInteger(), nullable=False),
        sa.Column("updated_ms", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_status_available_ms"), ["status", "available_ms"], unique=False)

    op.create_table(
        "judge_calls",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("judge_name", sa.String(), nullable=False),
        sa.Column("judge_version", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("input_hash", sa.String(), nullable=False),
        sa.Column("prompt_blob", sa.String(), nullable=True),
        sa.Column("response_blob", sa.String(), nullable=True),
        sa.Column("parsed", sa.JSON(), nullable=True),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("attempts", sa.BigInteger(), nullable=False),
        sa.Column("latency_ms", sa.BigInteger(), nullable=True),
        sa.Column("created_ms", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_judge_calls")),
    )
    with op.batch_alter_table("judge_calls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_judge_calls_judge_version_input_hash"), ["judge_version", "input_hash"], unique=False
        )

    op.create_table(
        "judges",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("prompt_hash", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("created_ms", sa.BigInteger(), nullable=False),
        sa.Column("trusted", sa.Boolean(), nullable=False),
        sa.Column("agreement", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("name", "version", name=op.f("pk_judges")),
    )
    op.create_table(
        "recorded_values",
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("trace_id", "seq", name=op.f("pk_recorded_values")),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("profile", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("started_ms", sa.BigInteger(), nullable=True),
        sa.Column("ended_ms", sa.BigInteger(), nullable=True),
        sa.Column("updated_ms", sa.BigInteger(), nullable=False),
        sa.Column("entry_request_blob", sa.String(), nullable=True),
        sa.Column("output_blob", sa.String(), nullable=True),
        sa.Column("input_text", sa.String(), nullable=True),
        sa.Column("output_text", sa.String(), nullable=True),
        sa.Column("ending", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("replayable", sa.Boolean(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("replay_of", sa.String(), nullable=True),
        sa.Column("remote_parent_span_id", sa.String(), nullable=True),
        sa.Column("step_count", sa.BigInteger(), nullable=False),
        sa.Column("input_tokens", sa.BigInteger(), nullable=False),
        sa.Column("output_tokens", sa.BigInteger(), nullable=False),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("trace_id", name=op.f("uq_runs_trace_id")),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_profile_started_ms"), ["profile", "started_ms"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_status"), ["status"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("source_run_id", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("fork_step", sa.BigInteger(), nullable=True),
        sa.Column("overrides", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_ms", sa.BigInteger(), nullable=False),
        sa.Column("ended_ms", sa.BigInteger(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("trace_id", name=op.f("uq_sessions_trace_id")),
    )
    op.create_table(
        "spans",
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("span_id", sa.String(length=16), nullable=False),
        sa.Column("parent_span_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("service", sa.String(), nullable=True),
        sa.Column("scope", sa.String(), nullable=True),
        sa.Column("start_ns", sa.BigInteger(), nullable=False),
        sa.Column("end_ns", sa.BigInteger(), nullable=False),
        sa.Column("status_code", sa.String(), nullable=False),
        sa.Column("status_message", sa.String(), nullable=True),
        sa.Column("flags", sa.BigInteger(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("events", sa.JSON(), nullable=False),
        sa.Column("resource", sa.JSON(), nullable=False),
        sa.Column("blob_refs", sa.JSON(), nullable=False),
        sa.Column("received_ms", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("trace_id", "span_id", name=op.f("pk_spans")),
    )
    with op.batch_alter_table("spans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_spans_trace_id"), ["trace_id"], unique=False)

    op.create_table(
        "suite_runs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("suite", sa.String(), nullable=False),
        sa.Column("baseline", sa.String(), nullable=True),
        sa.Column("candidate", sa.String(), nullable=True),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("verdict", sa.String(), nullable=True),
        sa.Column("report_blob", sa.String(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_ms", sa.BigInteger(), nullable=False),
        sa.Column("finished_ms", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suite_runs")),
    )
    op.create_table(
        "failures",
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("profile", sa.String(), nullable=False),
        sa.Column("signature", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("where_step", sa.BigInteger(), nullable=True),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.Column("cluster_id", sa.String(), nullable=True),
        sa.Column("created_ms", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_failures_run_id_runs"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_failures")),
    )
    with op.batch_alter_table("failures", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_failures_profile_cluster_id"), ["profile", "cluster_id"], unique=False)

    op.create_table(
        "labels",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("labeler", sa.String(), nullable=False),
        sa.Column("created_ms", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_labels_run_id_runs"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_labels")),
    )
    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_labels_run_id_question"), ["run_id", "question"], unique=False)

    op.create_table(
        "scores",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("value", sa.Double(), nullable=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("rationale", sa.String(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_ms", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_scores_run_id_runs"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scores")),
    )
    with op.batch_alter_table("scores", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scores_name_version"), ["name", "version"], unique=False)
        batch_op.create_index(batch_op.f("ix_scores_run_id"), ["run_id"], unique=False)

    op.create_table(
        "steps",
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("idx", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("node", sa.String(), nullable=True),
        sa.Column("exchange_id", sa.String(), nullable=True),
        sa.Column("span_id", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("tool_name", sa.String(), nullable=True),
        sa.Column("input_tokens", sa.BigInteger(), nullable=True),
        sa.Column("output_tokens", sa.BigInteger(), nullable=True),
        sa.Column("started_ms", sa.BigInteger(), nullable=True),
        sa.Column("latency_ms", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("view", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_steps_run_id_runs"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "idx", name=op.f("pk_steps")),
    )
    op.create_table(
        "suite_cases",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("suite_run_id", sa.String(length=26), nullable=False),
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("repeat", sa.BigInteger(), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("baseline_run_id", sa.String(), nullable=True),
        sa.Column("candidate_run_id", sa.String(), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["suite_run_id"], ["suite_runs.id"], name=op.f("fk_suite_cases_suite_run_id_suite_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suite_cases")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("suite_cases")
    op.drop_table("steps")
    with op.batch_alter_table("scores", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scores_run_id"))
        batch_op.drop_index(batch_op.f("ix_scores_name_version"))

    op.drop_table("scores")
    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_labels_run_id_question"))

    op.drop_table("labels")
    with op.batch_alter_table("failures", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_failures_profile_cluster_id"))

    op.drop_table("failures")
    op.drop_table("suite_runs")
    with op.batch_alter_table("spans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_spans_trace_id"))

    op.drop_table("spans")
    op.drop_table("sessions")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_status"))
        batch_op.drop_index(batch_op.f("ix_runs_profile_started_ms"))

    op.drop_table("runs")
    op.drop_table("recorded_values")
    op.drop_table("judges")
    with op.batch_alter_table("judge_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_judge_calls_judge_version_input_hash"))

    op.drop_table("judge_calls")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_status_available_ms"))

    op.drop_table("jobs")
    with op.batch_alter_table("exchanges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exchanges_trace_id_seq"))
        batch_op.drop_index(batch_op.f("ix_exchanges_session_id"))

    op.drop_table("exchanges")
    op.drop_table("clusters")
    op.drop_table("blobs")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_profile_rule_status"))

    op.drop_table("alerts")
    # ### end Alembic commands ###
